import type { Listing } from "../../../shared/types";

export async function getApartmentsListings(): Promise<Listing[]> {
  await new Promise(resolve => setTimeout(resolve, 200));

  return [
    {
      id: "apartments_1",
      title: "Cozy Studio Apartment",
      description: "Efficient studio layout with Murphy bed, modern kitchenette, and in-unit laundry. Great location near transit.",
      price: 1650,
      address: "321 Pine Street",
      city: "Portland",
      state: "OR",
      imageUrl: "https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?w=800",
      source: "apartments",
      bedrooms: 0,
      bathrooms: 1,
      sqft: 450,
      availableFrom: new Date(Date.now() + 3 * 24 * 60 * 60 * 1000).toISOString(),
      createdAt: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(),
    },
    {
      id: "apartments_2",
      title: "Urban 2BR with Balcony",
      description: "Bright apartment with private balcony overlooking the park. Includes dishwasher, AC, and secure bike storage.",
      price: 2400,
      address: "654 Park Boulevard",
      city: "Denver",
      state: "CO",
      imageUrl: "https://images.unsplash.com/photo-1460317442991-0ec209397118?w=800",
      source: "apartments",
      bedrooms: 2,
      bathrooms: 1,
      sqft: 950,
      availableFrom: new Date(Date.now() + 10 * 24 * 60 * 60 * 1000).toISOString(),
      createdAt: new Date(Date.now() - 4 * 24 * 60 * 60 * 1000).toISOString(),
    },
    {
      id: "apartments_3",
      title: "Garden Level 1BR",
      description: "Ground floor unit with direct patio access and garden view. Pet-friendly building with on-site management.",
      price: 1900,
      address: "987 Garden Way",
      city: "Boston",
      state: "MA",
      imageUrl: "https://images.unsplash.com/photo-1493809842364-78817add7ffb?w=800",
      source: "apartments",
      bedrooms: 1,
      bathrooms: 1,
      sqft: 700,
      availableFrom: new Date(Date.now() + 5 * 24 * 60 * 60 * 1000).toISOString(),
      createdAt: new Date(Date.now() - 6 * 24 * 60 * 60 * 1000).toISOString(),
    },
    {
      id: "apartments_4",
      title: "Renovated Historic Apartment",
      description: "Newly renovated unit in historic building combining original charm with modern amenities. Hardwood floors throughout.",
      price: 2200,
      address: "147 Heritage Lane",
      city: "Charleston",
      state: "SC",
      imageUrl: "https://images.unsplash.com/photo-1484154218962-a197022b5858?w=800",
      source: "apartments",
      bedrooms: 1,
      bathrooms: 1,
      sqft: 800,
      availableFrom: new Date(Date.now() + 28 * 24 * 60 * 60 * 1000).toISOString(),
      createdAt: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000).toISOString(),
    },
  ];
}
